server:
  servlet:
    context-path: /companies-crud
  port: 0
spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_name}
    username: ${db_username}
    password: ${db_password}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5