spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/companies-production
    username: postgres-production
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5